/*
You are given two strings s and t.
String t is generated by random shuffling string s and then 
add one more letter at a random position.
Return the letter that was added to t.
 
Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.
*/

#include<iostream>
#include<bits/stdc++.h>
#include<climits>
using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        int sum_s=0;int sum_t=0;
        for(int i=0;i<s.size();i++)sum_s+=s[i];;
        for(int i=0;i<t.size();i++)sum_t+=t[i];
        return abs(sum_s-sum_t); 
    }
};